version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html

