version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.10
  install:
    - requirements: requirements.txt

build:
  os: "ubuntu-22.04"
  commands:
    - pip install -r requirements.txt
    - sphinx-build -b html docs/ docs/_build/html

