version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "
      echo '🚀 MIGRATIONS' &&
      python manage.py migrate --noinput &&
      echo '📦 LOADDATA' &&
      python manage.py loaddata fixtures/users.json fixtures/lettings.json fixtures/profiles.json &&
      echo '🧹 COLLECTSTATIC' &&
      python manage.py collectstatic --noinput &&
      echo '🔥 Gunicorn Start' &&
      gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
      "
